variables:
  AVER: "3.7"         # Alpine version (must exist on Docker Hub)
  TB32:  "i386.zv.io" # unused; runs on Host (Docker)
  TB64: "amd64.zv.io" # unused; runs on Host (Docker)
  TBA7:   "arm.zv.io" #         runs on Host (native)
  TBA8:    "v8.zv.io" #         runs on Host (native)
  USER: "robot"       # should be unprivileged dummy account

#build:
#  cache:
#    paths:
#      - posix-utils/

test:TB32-alpine:
  image: i386/alpine:$AVER
  script:
  - apk update && apk add clang gcc make musl-dev
  - make gcctest
  - make clangtest

test:TB64-alpine:
  image: amd64/alpine:$AVER
  script:
  - apk update && apk add clang gcc make musl-dev
  - make gcctest
  - make clangtest
  
test:TB32-debian:
  image: i386/debian:$AVER
  script:
  - apt-get update && apt-get -y install clang gcc make
  - make gcctest
  - make clangtest

test:TB64-debian:
  image: amd64/debian:$AVER
  script:
  - apt-get update && apt-get -y install clang gcc make
  - make gcctest
  - make clangtest

# Copy and test on *remote* ARMv7 machine
test:TBA7:
  image: alpine:$AVER # Host environment
  script:
  - apk update && apk add bash openssh-client rsync
  - mkdir ~/.ssh
  - chmod 700 ~/.ssh
  - eval $(ssh-agent)
  - bash -c 'ssh-add <(echo "$ID_RSA")'
  - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
  - rsync -r . $USER@$TBA7:/home/$USER/$CI_COMMIT_SHA
  - ssh $USER@$TBA7 "cd /home/$USER/$CI_COMMIT_SHA && make gcctest && make clangtest && cd - && rm -fr /home/$USER/$CI_COMMIT_SHA"
  
# Copy and test on *remote* ARMv8 machine
test:TBA8:
  image: alpine:$AVER # Host environment
  script:
  - apk update && apk add bash openssh-client rsync
  - mkdir ~/.ssh
  - chmod 700 ~/.ssh
  - eval $(ssh-agent)
  - bash -c 'ssh-add <(echo "$ID_RSA")'
  - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
  - rsync -r . $USER@$TBA8:/home/$USER/$CI_COMMIT_SHA
  - ssh $USER@$TBA8 "cd /home/$USER/$CI_COMMIT_SHA && make gcctest && make clangtest && cd - && rm -fr /home/$USER/$CI_COMMIT_SHA"
