variables:
  AVER: "3.7"         # Alpine version (must exist on Docker Hub)
  DVER: "8"           # Debian version (must exist on Docker Hub)
  TB32:  "i386.zv.io" # unused; runs on Host (Docker)
  TB64: "    c.zv.io" #         runs on Host (native)
  TBA7:   "arm.zv.io" #         runs on Host (native)
  TBA8:    "v8.zv.io" #         runs on Host (native)
  NODe:   "nod.zv.io" #         runs on Host (native)
  USER: "robot"       # should be unprivileged dummy account

#build:
#  cache:
#    paths:
#      - posix-utils/

test:TB32-alpine-gcc:
  image: i386/alpine:$AVER
  script:
  - apk update && apk add make musl-dev gcc 
  - make gcctest

test:TB32-alpine-clang:
  image: i386/alpine:$AVER
  script:
  - apk update && apk add make musl-dev clang binutils
  - make clangtest
  
test:TB64-alpine-gcc:
  image: amd64/alpine:$AVER
  script:
  - apk update && apk add make musl-dev gcc 
  - make gcctest

test:TB64-alpine-clang:
  image: amd64/alpine:$AVER
  script:
  - apk update && apk add make musl-dev clang binutils
  - make clangtest
  
test:TB32-debian-gcc:
  image: i386/debian:$DVER
  script:
  - apt-get update && apt-get -y install make gcc
  - make gcctest

test:TB32-debian-clang:
  image: i386/debian:$DVER
  script:
  - apt-get update && apt-get -y install make clang binutils
  - make clangtest
  
test:TB64-debian-gcc:
  image: amd64/debian:$DVER
  script:
  - apt-get update && apt-get -y install make gcc
  - make gcctest

test:TB64-debian-clang:
  image: amd64/debian:$DVER
  script:
  - apt-get update && apt-get -y install make clang binutils
  - make clangtest

# Copy and test on *remote* ARMv7 machine
test:TBA7-gcc:
  image: alpine:$AVER # Host environment
  script:
  - apk update && apk add bash openssh-client rsync
  - mkdir ~/.ssh
  - chmod 700 ~/.ssh
  - eval $(ssh-agent)
  - bash -c 'ssh-add <(echo "$ID_RSA")'
  - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
  - rsync -r . $USER@$TBA7:/home/$USER/$CI_COMMIT_SHA
  - ssh $USER@$TBA7 "cd /home/$USER/$CI_COMMIT_SHA && make gcctest && cd - && rm -fr /home/$USER/$CI_COMMIT_SHA"

test:TBA7-clang:
  image: alpine:$AVER # Host environment
  script:
  - apk update && apk add bash openssh-client rsync
  - mkdir ~/.ssh
  - chmod 700 ~/.ssh
  - eval $(ssh-agent)
  - bash -c 'ssh-add <(echo "$ID_RSA")'
  - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
  - rsync -r . $USER@$TBA7:/home/$USER/$CI_COMMIT_SHA
  - ssh $USER@$TBA7 "cd /home/$USER/$CI_COMMIT_SHA && make clangtest && cd - && rm -fr /home/$USER/$CI_COMMIT_SHA"
  
# Copy and test on *remote* ARMv8 machine
test:TBA8-gcc:
  image: alpine:$AVER # Host environment
  script:
  - apk update && apk add bash openssh-client rsync
  - mkdir ~/.ssh
  - chmod 700 ~/.ssh
  - eval $(ssh-agent)
  - bash -c 'ssh-add <(echo "$ID_RSA")'
  - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
  - rsync -r . $USER@$TBA8:/home/$USER/$CI_COMMIT_SHA
  - ssh $USER@$TBA8 "cd /home/$USER/$CI_COMMIT_SHA && make gcctest && cd - && rm -fr /home/$USER/$CI_COMMIT_SHA"

test:TBA8-clang:
  image: alpine:$AVER # Host environment
  script:
  - apk update && apk add bash openssh-client rsync
  - mkdir ~/.ssh
  - chmod 700 ~/.ssh
  - eval $(ssh-agent)
  - bash -c 'ssh-add <(echo "$ID_RSA")'
  - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
  - rsync -r . $USER@$TBA8:/home/$USER/$CI_COMMIT_SHA
  - ssh $USER@$TBA8 "cd /home/$USER/$CI_COMMIT_SHA && make clangtest && cd - && rm -fr /home/$USER/$CI_COMMIT_SHA"
  
# Copy and test on *remote* x86_64 machine
test:TB64-gcc:
  image: alpine:$AVER # Host environment
  script:
  - apk update && apk add bash openssh-client rsync
  - mkdir ~/.ssh
  - chmod 700 ~/.ssh
  - eval $(ssh-agent)
  - bash -c 'ssh-add <(echo "$ID_RSA")'
  - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
  - rsync -r . $USER@$TB64:/home/$USER/$CI_COMMIT_SHA
  - ssh $USER@$TB64 "cd /home/$USER/$CI_COMMIT_SHA && make gcctest && cd - && rm -fr /home/$USER/$CI_COMMIT_SHA"
  
test:TB64-clang:
  image: alpine:$AVER # Host environment
  script:
  - apk update && apk add bash openssh-client rsync
  - mkdir ~/.ssh
  - chmod 700 ~/.ssh
  - eval $(ssh-agent)
  - bash -c 'ssh-add <(echo "$ID_RSA")'
  - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
  - rsync -r . $USER@$TB64:/home/$USER/$CI_COMMIT_SHA
  - ssh $USER@$TB64 "cd /home/$USER/$CI_COMMIT_SHA && make clangtest && cd - && rm -fr /home/$USER/$CI_COMMIT_SHA"
  
# Copy and test on *remote* NODe machine
test:NODe64-gcc:
  image: alpine:$AVER # Host environment
  script:
  - apk update && apk add bash openssh-client
  - mkdir ~/.ssh
  - chmod 700 ~/.ssh
  - eval $(ssh-agent)
  - bash -c 'ssh-add <(echo "$ID_RSA")'
  - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
  - ssh $USER@$NODe $CI_COMMIT_SHA