gcc113_aarch64:
  tags:
    - aarch64
    - gcc113
  before_script:
    - echo before
  script:
    - git clone https://git.hlibc.xyz/lab/hlibc/
    - cd hlibc && make gcctest



gcc75_x86_64:
  tags:
    - x86_64
    - gcc75
  script: "make gcctest"

gcc22_mips64:
  tags:
    - mips64
    - gcc22
  script: "make gcctest"

gcc45_i686:
  tags:
    - i686
    - gcc45
  script: "make gcctest"

gcc110_ppc64:
  tags:
    - ppc64
    - gcc110
  script: "make gcctest"



